### ISSUE TITLE
Is this a good place to send issues with the current website?

### ISSUE THREAD

**Issue by kwadroke** [quozl/www.netrek.org#1]
I've noticed some issues with bad links and old/broken info on the netrek.org website. Is this a good place to send issues/fixes, or would emailing the address on the webpage be better?

**Comment by quozl** [comment]
Thanks for the offer.  Either is fine.  Both Dave and I work on this when we can.  We take care not to clobber each other's work.  I've taken the latest changes into the repository here.  I suggest you make a few changes, make a pull request, give me time to review, merge, and upload.

**Comment by kwadroke** [comment]
Thanks. Will submit changes here then. 
I don't have a lot so far, IRC server changes from Freenode to Libera.Chat, some broken links, etc
